jobs:
  build:
    docker:
      - image: 'circleci/openjdk:11-jdk'
    steps:
      - checkout
      - run:
          name: Analyze on SonarCloud
          command: mvn verify sonar:sonar

  notify:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - slack/notify:
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "plain_text",
                      "text": "*This is a text notification*",
                      "emoji": true
                    }
                  ]
                }
              ]
            }
          event: always

orbs:
  jira: circleci/jira@1.3.0
  slack: circleci/slack@4.0
version: 2.1
workflows:
  build:
    jobs:
      - build:
          post-steps:
            - jira/notify
  main:
    jobs:
      - build:
          context: sonarcloud

  send-notification:
    jobs:
      - notify:
          context: slack-secrets
