jobs:
  build:
    docker:
      - image: 'circleci/openjdk:11-jdk'
    steps:
      - checkout
      - run:
          name: Analyze on SonarCloud
          command: mvn verify sonar:sonar

orbs:
  jira: circleci/jira@1.3.0
version: 2.1
workflows:
  build:
    jobs:
      - build:
          post-steps:
            - jira/notify
  main:
    jobs:
      - build:
          context: sonarcloud

