jobs:
  build:
    docker:
      - image: 'circleci/node:10'
    steps:
      - run: echo "hello"
orbs:
  jira: circleci/jira@1.0.5
version: 2.1
workflows:
  build:
    jobs:
      - build:
          post-steps:
            - jira/notify
